### ISSUE TITLE
Talkyard API?

### ISSUE THREAD

**Issue by Halo4356** [debiki/talkyard#35]
Hello! Is there any documentation regarding Talkyard's API? I am looking at integrating Talkyard into an application of mine and documentation of the various api endpoints would be helpful.

**Comment by kajmagnus** [comment]
There's no documentation. I can start writing & documenting? And then I would need to know, which parts of the API are of interest to you, maybe a bit about your higher level goals?

So I created this topic:  https://www.talkyard.io/-108/talkyard-api

I'm going to close this whole GitHub issuses section soon — better to have all discussions in just one place.
