### ISSUE TITLE
Signup form doesn't allow email address with domain that has hyphens

### ISSUE THREAD

**Issue by josephrocca** [debiki/talkyard#36]
Example:

![image](https://user-images.githubusercontent.com/1167575/44895943-186f1e80-ad29-11e8-9c32-147dcb29b7af.png)

**Comment by kajmagnus** [comment]
That's true, thanks for reporting. I've fixed this now in my work-in-progress branch. The fix will be included in the next version, probably early next week.

(A regex was, but should be:

```
/^[^@]+@[^-@\.]+\.[^@]+[^-@\.]$/        <— bad, no hyphens allowed
/^[^@]+@[^-@\.][^@\.]*\.[^@]+[^-@\.]$/   <— good
```
 )

**Comment by kajmagnus** [comment]
@josephrocca  I've released the new server version now; if you have a server running somewhere, it should auto upgrade, or probably already have, with this problem fixed.

**Comment by josephrocca** [comment]
Thanks! I don't actually use talkyard at the moment, but I love what you're doing here and will probably use in one of my projects at some point. You're doing important work! 👍

**Comment by kajmagnus** [comment]
@josephrocca  Ok & thanks for reporting this :- )

(I'll close this Issues section in a while, so ... say in 2 weeks, this topic will be 404 Not Found)
